### ISSUE TITLE
Playlist - Unauthorized for url

### ISSUE THREAD

**Issue by bascurtiz** [superdima05/tidalgrabber#3]
Region-block thingie?
I can reach that track '1442725' thru the website/player with my account (made with VPN set to UK).
![image](https://user-images.githubusercontent.com/34075088/53260254-585c0080-36d1-11e9-9c88-dcc0ce4784b4.png)

**Comment by dmitzsaz** [comment]
You tried to download using VPN? Or you created an account with VPN?

**Comment by bascurtiz** [comment]
Account created with VPN.
No VPN running when using your script.

**Comment by dmitzsaz** [comment]
Ok, can you give playlist id? Because I tried download single track, and it downloaded

**Comment by dmitzsaz** [comment]
My TIDAL Account was created using UK VPN

**Comment by bascurtiz** [comment]
https://listen.tidal.com/playlist/4ee0563e-3d8f-4a42-bc3e-5a2e6e3efaa7

**Comment by bascurtiz** [comment]
Ok that's weird, it's grayed out in the playlist for me.
When sharing the link of the track https://tidal.com/track/1442725, i can play it.

**Comment by dmitzsaz** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/16977314/53260837-96622000-36e3-11e9-9f89-453c6d297147.png">
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/16977314/53260868-ad087700-36e3-11e9-8616-4a9877aff45a.png">
I can play it, and script can download it.

**Comment by dmitzsaz** [comment]
Try to use VPN

**Comment by bascurtiz** [comment]
Playlist is made with Dutch account.
Will try to create/clone playlist on same UK account.

**Comment by bascurtiz** [comment]
![image](https://user-images.githubusercontent.com/34075088/53260965-2186ea00-36d3-11e9-9082-ce48cf3d529a.png)

**Comment by dmitzsaz** [comment]
OK, try

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/16977314/53260999-f8228a00-36e3-11e9-83dd-e98f4d996b55.png">

I used Python 2 version, but I think Python 3 version will work

**Comment by bascurtiz** [comment]
Will try VPN set to UK aswell.

**Comment by bascurtiz** [comment]
![image](https://user-images.githubusercontent.com/34075088/53261169-a4a84000-36d3-11e9-9085-5a2ea87d4715.png)

![image](https://user-images.githubusercontent.com/34075088/53261222-c275a500-36d3-11e9-8600-1b57e96eedeb.png)

Weird.

**Comment by dmitzsaz** [comment]
Do you have Russia VPN? Because, I am in Russia, and can play this track normally.

**Comment by dmitzsaz** [comment]
Can you play this track from album? Not from playlist.

**Comment by bascurtiz** [comment]
Dinner time. Be right back =)

**Comment by dmitzsaz** [comment]
OK.

**Comment by bascurtiz** [comment]
I can only play the 1st 30 seconds or preview.
When searching up the track using search in Tidl's webplayer, it doesn't show the track.
So yes, it's region-block.

![image](https://user-images.githubusercontent.com/34075088/53262827-f05ce880-36d7-11e9-9d73-b497de69b6bc.png)


When I imported the original playlist url with soundiiz and converted it to my UK account,
It's not 295 tracks, but 262 tracks. So it filters out the region-blocked ones, I bet.
https://listen.tidal.com/playlist/a015e869-07e9-4cbd-8052-eecafe412140

Will try VPN set to Russia for complete picture.

**Comment by dmitzsaz** [comment]
If it region-block, I can't fix it on script-side.

**Comment by dmitzsaz** [comment]
I will try this track in different countries.

**Comment by bascurtiz** [comment]
Windscribe + Tunnelbear not supporting Russia VPN in free version.

Solution 1: user should delete the grayed out tracks from playlist, before using your script.
Solution 2: catch the error with your script, and continue.

**Comment by bascurtiz** [comment]
I encountered this using playlist https://listen.tidal.com/playlist/a015e869-07e9-4cbd-8052-eecafe412140 
![image](https://user-images.githubusercontent.com/34075088/53263502-dd4b1800-36d9-11e9-8f63-a3f4a8c0b524.png)

**Comment by dmitzsaz** [comment]
This script can download only HI-FI tracks, this track "Movin Too Fast" isn't in Flac format, it in mp3.
You can see it in the url. The url contains ".m4a"

**Comment by dmitzsaz** [comment]
I can add check. If track in FLAC

**Comment by bascurtiz** [comment]
That would be great!
Otherwise, user has to first review which tracks are Hi-Fi: not ideal.

**Comment by dmitzsaz** [comment]
Ok, I will add this. But now I am trying to download this track using VPN

**Comment by dmitzsaz** [comment]
I can download this track using VPN. I tested 5 countries

**Comment by dmitzsaz** [comment]
Can you give me track id?

**Comment by bascurtiz** [comment]
https://gyazo.com/f23aa3000a2ea6020145a851d1787361
https://tidal.com/browse/track/1442725

**Comment by dmitzsaz** [comment]
I did the checks, I will check it and upload.

**Comment by dmitzsaz** [comment]
Try now

**Comment by bascurtiz** [comment]
https://gyazo.com/c6d15c9df6e7233055ac150c5a463ae4

So far So good^

**Comment by bascurtiz** [comment]
![image](https://user-images.githubusercontent.com/34075088/53270222-6c146080-36eb-11e9-99ff-32772ffb4a94.png)
There's ''Movin' Too Fast''

**Comment by bascurtiz** [comment]
Ouch...
![image](https://user-images.githubusercontent.com/34075088/53270255-86e6d500-36eb-11e9-8694-789832809cda.png)

**Comment by dmitzsaz** [comment]
I am going to fix it 👍

**Comment by dmitzsaz** [comment]
Can you download this track in browser, by direct link?

**Comment by dmitzsaz** [comment]
I updated python3 branch, please check it

**Comment by bascurtiz** [comment]
ok

**Comment by bascurtiz** [comment]
![image](https://user-images.githubusercontent.com/34075088/53271202-007fc280-36ee-11e9-806a-f902713e3d40.png)

**Comment by bascurtiz** [comment]
Will try to d/l that track on its own now.

**Comment by dmitzsaz** [comment]
I understood, maybe the problem with character "?"

**Comment by dmitzsaz** [comment]
What do you think about that?

**Comment by dmitzsaz** [comment]
Try to download this track, without playlist. ID of this track is "5917380"

**Comment by bascurtiz** [comment]
ok

**Comment by bascurtiz** [comment]
Same error.
It's defo a character thingie.
U know, UTF-8 vs. ANSI, something.
I can try on Mac, like u, to doublecheck?

![image](https://user-images.githubusercontent.com/34075088/53271670-73d60400-36ef-11e9-90fd-9c0f99652657.png)

**Comment by dmitzsaz** [comment]
I was trying on Mac, and it can be download

**Comment by dmitzsaz** [comment]
You can change one line

**Comment by bascurtiz** [comment]
oh ok, shoot.
installing Python at mac in between.

**Comment by dmitzsaz** [comment]
Try to change this line `name = translit(""+track.name, "ru", reversed=True)` to `name = translit(""+track.name, "ru", reversed=True).replace("?", "")`

**Comment by bascurtiz** [comment]
Works with above change!

**Comment by bascurtiz** [comment]
Will try to d/l playlist again, to see if there's no limitation.

**Comment by dmitzsaz** [comment]
ok

**Comment by bascurtiz** [comment]
Still going on strong on Windows/Playlist.

Never mind lol. NEVER use Texteditor on a .py file =)

**Comment by bascurtiz** [comment]
Prolly the " thingie?
![image](https://user-images.githubusercontent.com/34075088/53272959-f7452480-36f2-11e9-8464-f9e6e55cc8fe.png)

**Comment by dmitzsaz** [comment]
I know how to fix it

**Comment by dmitzsaz** [comment]
I will update script after 10 minutes

**Comment by dmitzsaz** [comment]
Yes, I only use Sublime Text 3 on Mac

**Comment by dmitzsaz** [comment]
I fixed it, try the new version of script.

**Comment by bascurtiz** [comment]
ok

**Comment by bascurtiz** [comment]
'music/Teardrops Lovestation Classic 12" Mix.flac'
fails again.
Copy/paste that " thingie from above, so u have the right character?

**Comment by bascurtiz** [comment]
I see the difficulty: .replace(""", "") is refused;
SyntaxError: EOF while scanning triple-quoted string literal
So u used .replace(")", "") instead, but doesn't catch it off, so it seems.

**Comment by dmitzsaz** [comment]
Ok, I will fix it later. Because now in Russia 01:21 am. And I want to sleep.

**Comment by bascurtiz** [comment]
Is ok bro, thanks for helping me out!
Good night.

**Comment by dmitzsaz** [comment]
Good night too

**Comment by bascurtiz** [comment]
adding .replace('"', "")
...does the trick!

**Comment by bascurtiz** [comment]
Playlist complete 👍 
Will try more playlists tomorrow.
![image](https://user-images.githubusercontent.com/34075088/53279824-0dafa800-3714-11e9-89c7-64e18c05537a.png)
