### ISSUE TITLE
m4a tracks are still d/led as flac without metadata

### ISSUE THREAD

**Issue by bascurtiz** [superdima05/tidalgrabber#4]
See picture below.
These tracks are n/a in lossless quality (so these are m4a), but they get the flac extension.
Also their metadata is missing.
They play however.

Possible solution 1: Skip the m4a tracks completely, not creating any file for them (incl. artwork).
Possible solution 2: If m4a detected, then name extension .m4a + embed artwork & metadata.

![image](https://user-images.githubusercontent.com/34075088/53285707-04e6c280-3764-11e9-8a06-565a5abc7c5b.png)

![image](https://user-images.githubusercontent.com/34075088/53285768-c3a2e280-3764-11e9-9e7f-af9c45d753c6.png)

**Comment by dmitzsaz** [comment]
Can you give me id of any .m4a track?

**Comment by dmitzsaz** [comment]
Try new update

**Comment by bascurtiz** [comment]
Yo, back.
Will test right away.

**Comment by bascurtiz** [comment]
All good now!

**Comment by bascurtiz** [comment]
FYI:
I thought there was something wrong with your app, check this tune:
https://tidal.com/track/93410808
Listen around 4:30 mins and 5:20 mins.
Happens on their webplayer too.
Just beware these exist.

**Comment by dmitzsaz** [comment]
If it happens on TIDAL player, it can be happens on my app

**Comment by bascurtiz** [comment]
Another issue: 
Can you reach https://listen.tidal.com/playlist/11b39f6c-60be-4eec-9e23-f402e8788fdd ?
I can, but your script says: playlist not found.

**Comment by dmitzsaz** [comment]
It is a bug of tidalapi, try to clone this playlist. I don't know how to fix it

**Comment by bascurtiz** [comment]
ok, just cloned it, will try now.

**Comment by bascurtiz** [comment]
https://tidal.com/browse/playlist/f1e72380-b8bd-4967-83e2-dbb26f4070cc

**Comment by bascurtiz** [comment]
it's d/ling ^
